### ISSUE TITLE
No method error

### ISSUE THREAD

**Issue by maykazw** [followerstracker/ahoy_admin#1]
I have NoMethodError at / undefined method `group_by_period' for #<ActiveRecord::Relation []> at displaying overwiew 
data_views-> () /ahoy_admin/overview_presenter.rb

**Comment by followerstracker** [comment]
Thanks for reporting! It should be fixed here ba30cc4. Although, It's not been released yet.

Feel free to reopen it if it is still an issue.

**Comment by maykazw** [comment]
I still have 
Ahoy::Event.method_missing
activerecord (6.0.5.1) lib/active_record/dynamic_matchers.rb, line 22
undefined method `with' for #<Class:0x00007fcac3896dc8>
when im trying to run admin site..

**Comment by followerstracker** [comment]
> I still have Ahoy::Event.method_missing activerecord (6.0.5.1) lib/active_record/dynamic_matchers.rb, line 22 undefined method `with' for #Class:0x00007fcac3896dc8 when im trying to run admin site..

That's strange. This method comes from https://github.com/GeorgeKaraszi/ActiveRecordExtended gem and it's specified as a dependency for ahoy_admin. Can you ensure you use the latest `main` branch. Also, it would be helpful if you post a few more lines of the backtrace.

**Comment by followerstracker** [comment]
Ah, it might be related to this issue https://github.com/GeorgeKaraszi/ActiveRecordExtended/issues/50, mind trying to update that gem?
